#!/usr/bin/env python3

"""Example based on pybullet_planning_tutorial generated by claude AI ( Anthropic )
"""

import numpy as np
import matplotlib.pyplot as plt
import pybullet as pb
from pybullet_planning import (
    connect,
    load_pybullet,
    get_movable_joints,
    get_joint_names,
    set_joint_positions,
    get_sample_fn,
    plan_joint_motion,
    get_collision_fn,
    waypoints_from_path,
    wait_for_user,
    wait_for_duration,
    create_obj,
)
from pathlib import Path

from src.logger import DataStore
from src.kinematics import forward_kinematics_matrix
from src.transformation import load_obj2robot, extract_pybullet_pose
from src.config import OBSTACLE_STLS

# ---------------------------------------------------------------------------
# Paths (same as in safety.py / config.py)
# ---------------------------------------------------------------------------
HERE = Path(__file__).resolve().parent
URDF_PATH = HERE / "duckify_simulation" / "urdf" / "ur3e.urdf"

# ---------------------------------------------------------------------------
# Obstacle placement — same as pybullet_collision_test.py
# ---------------------------------------------------------------------------
record = DataStore()
obj2robot = load_obj2robot(record)
pos, quat, scale = extract_pybullet_pose(obj2robot)
for obs in OBSTACLE_STLS:
    if 'position' not in obs:
        obs['position'] = pos
        obs['orientation'] = quat

print(f"Obstacle pose: pos={pos}, quat={quat}")

# ---------------------------------------------------------------------------
# 1. Start PyBullet with GUI
# ---------------------------------------------------------------------------
# pybullet_planning's connect() returns a physics client id
cid = connect(use_gui=True)

# ---------------------------------------------------------------------------
# 2. Load the UR3e robot (same orientation as safety.py: pi rotation around Z)
# ---------------------------------------------------------------------------
robot = pb.loadURDF(
    str(URDF_PATH),
    basePosition=[0, 0, 0],
    baseOrientation=pb.getQuaternionFromEuler([0, 0, np.pi]),
    useFixedBase=True,
)
joints = get_movable_joints(robot)
joint_names = get_joint_names(robot, joints)
print(f"\nRobot loaded (id={robot})")
print(f"Movable joints: {joints}")
print(f"Joint names:    {joint_names}")

# ---------------------------------------------------------------------------
# 3. Load obstacles as collision shapes (same as CollisionChecker.__init__)
# ---------------------------------------------------------------------------
def load_obstacle_stl(stl_path, mesh_scale, position, orientation):
    """Load an STL as a static collision + visual body, returns body id."""
    col = pb.createCollisionShape(
        pb.GEOM_MESH,
        fileName=str(stl_path),
        meshScale=mesh_scale,
        flags=pb.GEOM_FORCE_CONCAVE_TRIMESH,
    )
    vis = pb.createVisualShape(
        pb.GEOM_MESH,
        fileName=str(stl_path),
        meshScale=mesh_scale,
        rgbaColor=[0.6, 0.6, 0.8, 0.7],
    )
    body = pb.createMultiBody(
        baseMass=0,
        baseCollisionShapeIndex=col,
        baseVisualShapeIndex=vis,
        basePosition=position,
        baseOrientation=orientation,
    )
    return body

# ---------------------------------------------------------------------------
# Helper: move robot and draw an orange sphere at the TCP
# ---------------------------------------------------------------------------
tcp_sphere_ids = []

def move_and_mark(robot_id, joint_ids, q, T_offset):
    """Set joint positions and draw an orange sphere at the pen tip."""
    set_joint_positions(robot_id, joint_ids, q)
    T_flange = forward_kinematics_matrix(list(q))
    T_tcp = T_flange @ T_offset
    tcp_pos = T_tcp[:3, 3].tolist()
    vis = pb.createVisualShape(pb.GEOM_SPHERE, radius=0.001, rgbaColor=[1, 0.5, 0, 1])
    bid = pb.createMultiBody(baseMass=0, baseVisualShapeIndex=vis, basePosition=tcp_pos)
    tcp_sphere_ids.append(bid)

# Load obstacles from OBSTACLE_STLS (same config as pybullet_collision_test.py)
obstacles = []
for obs in OBSTACLE_STLS:
    oid = load_obstacle_stl(
        obs['path'],
        obs.get('scale', [1, 1, 1]),
        obs.get('position', [0, 0, 0]),
        obs.get('orientation', [0, 0, 0, 1]),
    )
    obstacles.append(oid)
    print(f"  Obstacle {oid}: {obs['path']}")
print(f"\nObstacles loaded: {obstacles}")

# ---------------------------------------------------------------------------
# 4. Camera
# ---------------------------------------------------------------------------
pb.resetDebugVisualizerCamera(
    cameraDistance=0.6, cameraYaw=45, cameraPitch=-30,
    cameraTargetPosition=pos,
)

# ---------------------------------------------------------------------------
# 5. Set robot to home position
# ---------------------------------------------------------------------------
# home = [1.8859, -1.4452, 1.2389, -1.3639, -1.5693, -0.3849]
home = [1.8859, -1.4452, 1.2389, 1.7707, 1.5693, -0.3849]
# set_joint_positions(robot, joints, home)
# move_and_mark(robot, joints, home)
print(f"\nRobot set to home: {home}")

# ---------------------------------------------------------------------------
# 6. Load waypoints from pickle
# ---------------------------------------------------------------------------
waypoints = record.load_waypoints(file_path="save_data/waypoints_47.pkl")

print(f"\nLoaded {len(waypoints)} waypoints (Joint6D)")
print("First 10 waypoints:")
for i, wp in enumerate(waypoints[:10]):
    print(f"  [{i}] {wp.toList()}")

# Load TCP offset (pen tip offset from flange) and build 4x4 matrix
_, tcp_offset = record.load_calibration("save_data/calibration_default.pkl")
T_tcp_offset = np.eye(4)
T_tcp_offset[0, 3] = tcp_offset.x  # ~0.0001
T_tcp_offset[1, 3] = tcp_offset.y  # ~0.0003
T_tcp_offset[2, 3] = tcp_offset.z  # ~0.2453
print(f"TCP offset: x={tcp_offset.x:.4f}, y={tcp_offset.y:.4f}, z={tcp_offset.z:.4f}")


move_and_mark(robot, joints, home, T_tcp_offset)

# # Draw an orange sphere at the TCP (pen tip) for every loaded waypoint
# print(f"\nDrawing {len(waypoints)} TCP spheres...")
# for wp in waypoints:
#     q = wp.toList()
#     T_flange = forward_kinematics_matrix(q)
#     T_tcp = T_flange @ T_tcp_offset
#     tcp_pos = T_tcp[:3, 3].tolist()
#     vis = pb.createVisualShape(pb.GEOM_SPHERE, radius=0.001, rgbaColor=[1, 0.5, 0, 1])
#     pb.createMultiBody(baseMass=0, baseVisualShapeIndex=vis, basePosition=tcp_pos)
# print("TCP spheres drawn.")
# set_joint_positions(robot, joints, home)

# ---------------------------------------------------------------------------
# 7. Shortcutting helper
# ---------------------------------------------------------------------------
collision_fn = get_collision_fn(robot, joints, obstacles=obstacles, self_collisions=True)

def shortcut_path(raw_path, collision_fn, num_steps=20):
    """Greedily skip waypoints if the straight line between them is collision-free."""
    short = [raw_path[0]]
    i = 0
    while i < len(raw_path) - 1:
        best_j = i + 1
        for j in range(len(raw_path) - 1, i + 1, -1):
            q_start = np.array(raw_path[i])
            q_end = np.array(raw_path[j])
            clear = True
            for step in range(1, num_steps + 1):
                t = step / num_steps
                q_mid = q_start + t * (q_end - q_start)
                if collision_fn(tuple(q_mid)):
                    clear = False
                    break
            if clear:
                best_j = j
                break
        short.append(raw_path[best_j])
        i = best_j
    return short

def animate_path(path, T_offset, steps=20, delay=0.02, draw_spheres=True):
    """Smoothly animate a path by interpolating between waypoints."""
    for i in range(len(path) - 1):
        q_start = np.array(path[i])
        q_end = np.array(path[i + 1])
        for step in range(steps):
            t = step / steps
            q_interp = q_start + t * (q_end - q_start)
            if draw_spheres:
                move_and_mark(robot, joints, q_interp.tolist(), T_offset)
            else:
                set_joint_positions(robot, joints, q_interp.tolist())
            wait_for_duration(delay)
    if draw_spheres:
        move_and_mark(robot, joints, path[-1], T_offset)
    else:
        set_joint_positions(robot, joints, list(path[-1]))

# ---------------------------------------------------------------------------
# 8. Plan between every consecutive pair of waypoints
# ---------------------------------------------------------------------------
# Build the list of configs: home -> wp0 -> wp1 -> ... -> wpN -> home
configs = [home] + [wp.toList() for wp in waypoints] + [home]

print(f"\n{len(configs)} configs to visit (home + {len(waypoints)} waypoints + home)")
input("ENTER to start planning all pairs")

move_and_mark(robot, joints, configs[0], T_tcp_offset)

all_planned_paths = []
failed_pairs = []  # list of (pair_index, conf_A, conf_B, reason)

for i in range(len(configs) - 1):
    conf_A = configs[i]
    conf_B = configs[i + 1]

    print(f"\n--- Pair {i}/{len(configs)-2}: planning... ", end="", flush=True)
    set_joint_positions(robot, joints, conf_A)

    # Check if start or end are in collision before planning
    a_collision = collision_fn(tuple(conf_A))
    b_collision = collision_fn(tuple(conf_B))

    if a_collision or b_collision:
        reason = []
        if a_collision:
            reason.append("conf_A in collision")
        if b_collision:
            reason.append("conf_B in collision")
        reason_str = " & ".join(reason)
        print(f"FAILED ({reason_str})")
        failed_pairs.append((i, conf_A, conf_B, reason_str))
        all_planned_paths.append([conf_A, conf_B])
        continue

    path = plan_joint_motion(
        robot, joints, conf_B,
        obstacles=obstacles,
        self_collisions=True,
    )

    if path is None:
        print(f"FAILED (no path found)")
        failed_pairs.append((i, conf_A, conf_B, "no path found"))
        all_planned_paths.append([conf_A, conf_B])
    else:
        path = shortcut_path(path, collision_fn)
        path = waypoints_from_path(path)
        print(f"OK ({len(path)} wps)")
        all_planned_paths.append(path)

# Summary
total_wps = sum(len(p) for p in all_planned_paths)
print(f"\n{'=' * 60}")
print(f"Planning done: {len(all_planned_paths)} segments, {total_wps} total waypoints")
if failed_pairs:
    print(f"WARNING: {len(failed_pairs)} pairs failed: {[f[0] for f in failed_pairs]}")
print(f"{'=' * 60}")

# Animate all
wait_for_user()
print("Animating full trajectory...")
for i, path in enumerate(all_planned_paths):
    print(f"  Segment {i} ({len(path)} wps)")
    animate_path(path, T_tcp_offset)
print("Done!")

# ---------------------------------------------------------------------------
# 9. Replay: fast animation without erasing spheres
# ---------------------------------------------------------------------------
wait_for_user()
print("Replaying full trajectory (smooth, no new spheres)...")
set_joint_positions(robot, joints, configs[0])

# Stitch all planned paths into one continuous joint trajectory
full_trajectory = []
for path in all_planned_paths:
    for conf in path:
        full_trajectory.append(conf)

# Interpolate between every consecutive config and record all angles
REPLAY_STEPS = 30   # steps between each pair (more = smoother)
REPLAY_DELAY = 0.01 # seconds per step
recorded_angles = []  # every interpolated config gets stored here
waypoint_indices = [] # indices in recorded_angles where planner waypoints are

print(f"  {len(full_trajectory)} configs, interpolating {REPLAY_STEPS} steps each...")
for i in range(len(full_trajectory) - 1):
    q_start = np.array(full_trajectory[i])
    q_end = np.array(full_trajectory[i + 1])
    waypoint_indices.append(len(recorded_angles))
    for step in range(REPLAY_STEPS):
        t = step / REPLAY_STEPS
        q_interp = q_start + t * (q_end - q_start)
        recorded_angles.append(q_interp.tolist())
        set_joint_positions(robot, joints, q_interp.tolist())
        wait_for_duration(REPLAY_DELAY)
# Final config
waypoint_indices.append(len(recorded_angles))
recorded_angles.append(list(full_trajectory[-1]))
set_joint_positions(robot, joints, list(full_trajectory[-1]))
print("Replay done!")

# ---------------------------------------------------------------------------
# 9b. Plot joint angles over time
# ---------------------------------------------------------------------------
joint_labels = ["J1 shoulder_pan", "J2 shoulder_lift", "J3 elbow",
                "J4 wrist_1", "J5 wrist_2", "J6 wrist_3"]
angles_matrix = np.array(recorded_angles)

fig, axes = plt.subplots(6, 1, figsize=(14, 10), sharex=True, sharey=True)
fig.suptitle("Joint angles — full interpolated trajectory", fontsize=12)
y_min = angles_matrix.min() - 0.1
y_max = angles_matrix.max() + 0.1
for j in range(6):
    axes[j].plot(angles_matrix[:, j], linewidth=0.8, color="C0")
    # Mark planner waypoints
    for wi in waypoint_indices:
        axes[j].axvline(x=wi, color="gray", linewidth=0.3, alpha=0.5)
    axes[j].set_ylabel(f"{joint_labels[j]}\n(rad)", fontsize=8)
    axes[j].set_ylim(y_min, y_max)
    axes[j].grid(True, alpha=0.3)
axes[-1].set_xlabel("Interpolated step")
plt.tight_layout()
plt.show(block=False)
print("Joint plot displayed (close window or press ENTER to continue).")
input()

# ---------------------------------------------------------------------------
# 10. Inspect failed pairs one by one
# ---------------------------------------------------------------------------
if failed_pairs:
    print(f"\n{'=' * 60}")
    print(f"INSPECTING {len(failed_pairs)} FAILED PAIRS")
    print(f"{'=' * 60}")
    print("Press ENTER to step through each failed pair.\n")

    for idx, (pair_i, conf_A, conf_B, reason) in enumerate(failed_pairs):
        print(f"--- Failure {idx+1}/{len(failed_pairs)} | Pair {pair_i} | {reason} ---")

        # Show conf_A
        print(f"  conf_A (red sphere): moving robot...")
        set_joint_positions(robot, joints, conf_A)
        T_flange_a = forward_kinematics_matrix(conf_A)
        tcp_a = (T_flange_a @ T_tcp_offset)[:3, 3].tolist()
        vis_a = pb.createVisualShape(pb.GEOM_SPHERE, radius=0.002, rgbaColor=[1, 0, 0, 1])
        pb.createMultiBody(baseMass=0, baseVisualShapeIndex=vis_a, basePosition=tcp_a)
        print(f"    TCP_A = [{tcp_a[0]:.4f}, {tcp_a[1]:.4f}, {tcp_a[2]:.4f}]")
        input("  Press ENTER to see conf_B...")

        # Show conf_B
        print(f"  conf_B (blue sphere): moving robot...")
        set_joint_positions(robot, joints, conf_B)
        T_flange_b = forward_kinematics_matrix(conf_B)
        tcp_b = (T_flange_b @ T_tcp_offset)[:3, 3].tolist()
        vis_b = pb.createVisualShape(pb.GEOM_SPHERE, radius=0.002, rgbaColor=[0, 0, 1, 1])
        pb.createMultiBody(baseMass=0, baseVisualShapeIndex=vis_b, basePosition=tcp_b)
        print(f"    TCP_B = [{tcp_b[0]:.4f}, {tcp_b[1]:.4f}, {tcp_b[2]:.4f}]")

        if idx < len(failed_pairs) - 1:
            input("  Press ENTER for next failure...")
        else:
            print("  (last failure)")

    print(f"\nAll {len(failed_pairs)} failures inspected.")
else:
    print("\nNo failures to inspect!")

wait_for_user()

# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------
pb.disconnect()
print("PyBullet disconnected.")